---
# Per environment values which override defaults in hmpps-github-actions-runner/values.yaml
generic-service:
  nameOverride: hmpps-github-actions-runner-security-pod-1

  volumes:
    - name: security-runners-cache
      persistentVolumeClaim:
        claimName: security-runners-cache-1

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts
  targetApplication: hmpps-github-actions-runner-security-pod-1

