name: Build -> Deploy pipeline

on:
  push:
    branches:
      - 'main'
      - 'fix/**'
      - 'feat/**'
      - 'feature/**'

jobs:
  # This uses the same base as hmpps-github-actions-runner
  build-runner:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      packages: write
    name: Build
    uses: ./.github/workflows/build-runner.yml
    with:
      push: true
    secrets: inherit 
    
  # Deploy the pods individually so they can use separate API keys
  deploy-to-prod-pod-1:
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yml
    needs:
      - build-runner
    with:
      environment: production
      version: 'latest-prod'
      pod_number: 1
    secrets: inherit
    permissions:
      contents: read
      deployments: write
      pull-requests: write

  runner-cleanup:
    name: Remove old runners
    uses: ./.github/workflows/runner-cleanup.yml
    needs: deploy-to-prod-pod-1
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write